import XCTest
@testable import Lazy_Switcher

/// The one control that makes automatic updating defensible.
///
/// Everything else about the updater is plumbing. This is the part that decides
/// whether a program with Accessibility permission may replace its own binary:
/// the download has to satisfy the designated requirement of the **running**
/// application — same identifier, same certificate. The private key for that
/// certificate exists in one keychain and is published nowhere, so a release
/// swapped on GitHub, a hijacked domain or an intercepted connection all fail
/// here rather than at the user's expense.
///
/// If these tests ever stop passing, automatic updating has to be turned off,
/// not debugged around.
final class UpdaterSignatureTests: XCTestCase {

    /// We satisfy our own requirement. Trivially true and worth pinning: a
    /// verification that rejects everything is as broken as one that accepts
    /// everything, and looks safer.
    func testOurOwnBundlePasses() {
        let problem = Updater.signatureProblem(of: Bundle.main.bundleURL)
        XCTAssertNil(problem, "Собственный бандл обязан проходить проверку: \(problem ?? "")")
    }

    /// An Apple-signed application is signed perfectly well — and is not us.
    /// A check that only asked "is the signature valid" would accept this.
    func testAValidlySignedButDifferentApplicationIsRejected() throws {
        let candidates = ["/System/Applications/TextEdit.app",
                          "/System/Applications/Calculator.app",
                          "/System/Applications/Chess.app"]
        guard let other = candidates.first(where: { FileManager.default.fileExists(atPath: $0) })
        else { throw XCTSkip("Не нашлось системного приложения для проверки") }

        let problem = Updater.signatureProblem(of: URL(fileURLWithPath: other))
        XCTAssertNotNil(problem,
                        "Чужое приложение с исправной подписью Apple обязано быть отвергнуто — "
                      + "иначе проверяется валидность подписи, а не то, наша ли она")
    }

    /// Something with no signature at all.
    func testUnsignedDirectoryIsRejected() throws {
        let fake = FileManager.default.temporaryDirectory
            .appendingPathComponent("NotAnApp-\(UUID().uuidString).app")
        try FileManager.default.createDirectory(at: fake, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: fake) }
        XCTAssertNotNil(Updater.signatureProblem(of: fake))
    }

    func testMissingPathIsRejected() {
        let missing = URL(fileURLWithPath: "/tmp/definitely-not-here-\(UUID().uuidString).app")
        XCTAssertNotNil(Updater.signatureProblem(of: missing))
    }

    /// Updating in place has to write where we live. Anywhere else and we would
    /// be installing over something that is not the app the user runs — a copy
    /// in Downloads, or a translocated read-only mount.
    func testUpdatingIsRefusedOutsideApplications() {
        // The test host runs from DerivedData, which is exactly such a place.
        let expectation = expectation(description: "отказ")
        Updater.downloadAndInstall(progress: { _ in }) { result in
            if case .failure(.notInApplications) = result {
                expectation.fulfill()
            } else {
                XCTFail("Ожидали отказ из-за пути, получили \(result)")
                expectation.fulfill()
            }
        }
        wait(for: [expectation], timeout: 5)
    }
}

/// The swap, run against dummy bundles.
///
/// This is the only part of the app that deletes an application, and it runs
/// unattended on somebody's machine at the moment they are least able to react.
/// "It looked right" is not an acceptable standard for it, so the script is
/// generated by a testable function and exercised here on directories that are
/// not the real thing.
final class UpdaterHandOffTests: XCTestCase {

    private var sandbox: URL!

    override func setUpWithError() throws {
        try super.setUpWithError()
        sandbox = FileManager.default.temporaryDirectory
            .appendingPathComponent("handoff-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: sandbox, withIntermediateDirectories: true)
    }

    override func tearDown() {
        try? FileManager.default.removeItem(at: sandbox)
        super.tearDown()
    }

    private func makeBundle(_ name: String, marker: String) throws -> URL {
        let url = sandbox.appendingPathComponent(name)
        try FileManager.default.createDirectory(at: url.appendingPathComponent("Contents"),
                                                withIntermediateDirectories: true)
        try marker.write(to: url.appendingPathComponent("Contents/version.txt"),
                         atomically: true, encoding: .utf8)
        return url
    }

    private func marker(_ bundle: URL) -> String? {
        try? String(contentsOf: bundle.appendingPathComponent("Contents/version.txt"),
                    encoding: .utf8)
    }

    /// The script must not touch anything while the app is still running, and
    /// must give up rather than proceed if it never exits.
    ///
    /// `pid: 1` is launchd, which never exits and which an ordinary user cannot
    /// signal. That second property is what caught the original defect: the wait
    /// loop used `kill -0`, which fails both for a process that is gone and for
    /// one that is merely out of reach — so it concluded the app had quit and
    /// started replacing the bundle underneath it.
    func testNothingIsTouchedWhileTheAppIsStillAlive() throws {
        let installed = try makeBundle("Installed.app", marker: "old")
        let staged = try makeBundle("Staged.app", marker: "new")
        let backup = sandbox.appendingPathComponent(".previous.app")

        let script = Updater.handOffScript(destination: installed, staged: staged,
                                           backup: backup, pid: 1)
        // Ten seconds of waiting, then the move — we only care about the first
        // second, so the script is killed before it gets there.
        let path = sandbox.appendingPathComponent("run.sh")
        try script.write(to: path, atomically: true, encoding: .utf8)
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/bash")
        process.arguments = [path.path]
        try process.run()
        Thread.sleep(forTimeInterval: 1.5)
        XCTAssertEqual(marker(installed), "old", "Приложение тронули, пока оно ещё работало")
        XCTAssertEqual(marker(staged), "new")
        process.terminate()
    }

    /// And when the wait runs out, it refuses rather than proceeding.
    func testItGivesUpRatherThanSwappingUnderALiveProcess() throws {
        let installed = try makeBundle("Installed.app", marker: "old")
        let staged = try makeBundle("Staged.app", marker: "new")
        let backup = sandbox.appendingPathComponent(".previous.app")

        var script = Updater.handOffScript(destination: installed, staged: staged,
                                           backup: backup, pid: 1)
        // Shorten the wait so the test does not sit for ten seconds.
        script = script.replacingOccurrences(of: "$(seq 1 100)", with: "$(seq 1 3)")
        let path = sandbox.appendingPathComponent("run.sh")
        try script.write(to: path, atomically: true, encoding: .utf8)

        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/bash")
        process.arguments = [path.path]
        process.standardError = Pipe()
        try process.run()
        process.waitUntilExit()

        XCTAssertNotEqual(process.terminationStatus, 0, "Сценарий обязан отказаться")
        XCTAssertEqual(marker(installed), "old", "Бандл обязан остаться нетронутым")
    }

    /// The swap itself, with a process id that is already gone.
    func testSwapReplacesTheBundleAndRemovesTheBackup() throws {
        let installed = try makeBundle("Installed.app", marker: "old")
        let staged = try makeBundle("Staged.app", marker: "new")
        let backup = sandbox.appendingPathComponent(".previous.app")

        // A pid that has certainly exited: our own child, run and reaped.
        let dead = Process()
        dead.executableURL = URL(fileURLWithPath: "/usr/bin/true")
        try dead.run()
        dead.waitUntilExit()

        var script = Updater.handOffScript(destination: installed, staged: staged,
                                           backup: backup, pid: dead.processIdentifier)
        // Drop the relaunch: there is no application here to open.
        script = script.replacingOccurrences(of: "open \"\(installed.path)\"", with: "true")
        let path = sandbox.appendingPathComponent("run.sh")
        try script.write(to: path, atomically: true, encoding: .utf8)

        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/bash")
        process.arguments = [path.path]
        try process.run()
        process.waitUntilExit()

        XCTAssertEqual(process.terminationStatus, 0)
        XCTAssertEqual(marker(installed), "new", "Новая версия должна оказаться на месте старой")
        XCTAssertFalse(FileManager.default.fileExists(atPath: backup.path),
                       "Резервная копия должна быть убрана после успеха")
        XCTAssertFalse(FileManager.default.fileExists(atPath: staged.path),
                       "Подготовленная копия должна быть перемещена, а не скопирована")
    }

    /// If the move fails, the previous version comes back. A failure at the
    /// worst moment has to leave a working application, not none.
    func testFailedSwapRestoresThePreviousVersion() throws {
        let installed = try makeBundle("Installed.app", marker: "old")
        let backup = sandbox.appendingPathComponent(".previous.app")
        // Staged path that does not exist: the second move cannot succeed.
        let missing = sandbox.appendingPathComponent("NotThere.app")

        let dead = Process()
        dead.executableURL = URL(fileURLWithPath: "/usr/bin/true")
        try dead.run()
        dead.waitUntilExit()

        let script = Updater.handOffScript(destination: installed, staged: missing,
                                           backup: backup, pid: dead.processIdentifier)
        let path = sandbox.appendingPathComponent("run.sh")
        try script.write(to: path, atomically: true, encoding: .utf8)

        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/bash")
        process.arguments = [path.path]
        try process.run()
        process.waitUntilExit()

        XCTAssertNotEqual(process.terminationStatus, 0, "Сценарий обязан сообщить о провале")
        XCTAssertEqual(marker(installed), "old",
                       "После неудачи прежняя версия обязана вернуться на место")
    }
}
